/* showcase.data.js · 展示页数据：路由、Element Plus 组件清单（按官方分类）、自研组件、布局范式、token 说明
 * 演示模板由 Vue 运行时编译（字符串模板），可自闭合。每条：key / cat / name / cn / demo / tokens / usage / init? / note? / wide? / command? / tags? */
window.DS_SHOWCASE = (() => {
  const ROUTES = [
    { key: 'tokens', label: '设计变量' },
    { key: 'materials', label: '组件物料' },
    { key: 'custom', label: '自研组件' },
    { key: 'layout', label: '布局范式' },
    { key: 'templates', label: '布局配置' },
  ]

  /* 自研组件分组：外壳 / 页面级 / 复合组件 */
  const CUSTOM_GROUPS = [
    { key: 'shell', label: '外壳', desc: '应用级容器，固定视口高，侧栏与主区各自 ElScrollbar 内滚' },
    { key: 'page', label: '页面级', desc: '页头与状态容器，每个页面都会用到' },
    { key: 'composite', label: '复合组件', desc: '结构级下沉 · 由原型中的候选结构（data-composite）提炼' },
  ]

  const CATEGORIES = [
    { key: 'basic', label: 'Basic 基础' },
    { key: 'config', label: 'Config 配置' },
    { key: 'form', label: 'Form 表单' },
    { key: 'data', label: 'Data 数据展示' },
    { key: 'nav', label: 'Navigation 导航' },
    { key: 'feedback', label: 'Feedback 反馈' },
    { key: 'others', label: 'Others 其他' },
  ]

  const SAMPLE = {
    opts: [{ value: 'pending', label: '待处理' }, { value: 'done', label: '已完成' }, { value: 'cancelled', label: '已取消' }],
    rows: [
      { no: 'SO-20260901-001', customer: '成都示例科技', amount: 12800, status: 'pending', date: '2026-09-01' },
      { no: 'SO-20260901-002', customer: '绵阳示例贸易', amount: 3200, status: 'done', date: '2026-09-01' },
      { no: 'SO-20260901-003', customer: '四川省某某某某某某某某科技发展有限责任公司', amount: 56000, status: 'cancelled', date: '2026-08-30' },
    ],
    tree: [{ id: 1, label: '订单管理', children: [{ id: 11, label: '订单列表' }, { id: 12, label: '退货处理' }] }, { id: 2, label: '客户管理', children: [{ id: 21, label: '客户列表' }] }, { id: 3, label: '报表' }],
    cascade: [{ value: 'sc', label: '四川', children: [{ value: 'cd', label: '成都', children: [{ value: 'gx', label: '高新区' }, { value: 'wh', label: '武侯区' }] }, { value: 'my', label: '绵阳' }] }, { value: 'cq', label: '重庆', children: [{ value: 'yz', label: '渝中区' }] }],
    list: ['成都示例科技', '绵阳示例贸易', '德阳示例机械', '乐山示例能源'],
    transfer: Array.from({ length: 8 }, (_, i) => ({ key: i, label: `客户 ${i + 1}` })),
    steps: ['提交订单', '审核', '发货', '完成'],
    tags: ['标签一', '标签二', '标签三'],
    menu: [
      { key: 'dashboard', label: '运营工作台' }, { key: 'monitor', label: '运行监测' }, { key: 'company', label: '企业档案' },
      { key: 'device', label: '设备台账' }, { key: 'org', label: '组织与片区' }, { key: 'env', label: '环境监测' }, { key: 'risk', label: '风险预警' },
    ],
    history: ['运营工作台', '企业档案', '运行监测', '组织与片区', '环境监测'],
    big: Array.from({ length: 200 }, (_, i) => ({ id: i, no: `SO-${String(i + 1).padStart(4, '0')}`, customer: `批量客户 ${i + 1}`, amount: (i * 37) % 10000 })),
    cols: [{ key: 'no', dataKey: 'no', title: '单号', width: 160 }, { key: 'customer', dataKey: 'customer', title: '客户', width: 200 }, { key: 'amount', dataKey: 'amount', title: '金额', width: 120, align: 'right' }],
  }

  const COMPONENTS = [
    /* ---------------- Basic ---------------- */
    { key: 'button', cat: 'basic', name: 'Button', cn: '按钮', wide: true, tokens: ['--color-primary', '--color-primary-hover', '--color-danger', '--radius-md', '--font-size-body', '--space-component-gap'], usage: '<el-button type="primary">主要</el-button>',
      demo: `<div class="ds-row"><el-button>默认</el-button><el-button type="primary">主要</el-button><el-button type="success">成功</el-button><el-button type="warning">警告</el-button><el-button type="danger">危险</el-button><el-button type="info">信息</el-button></div>
             <div class="ds-row"><el-button plain>朴素</el-button><el-button type="primary" plain>主要朴素</el-button><el-button type="primary" text>文字</el-button><el-button type="primary" link>链接</el-button><el-button type="primary" disabled>禁用</el-button><el-button type="primary" loading>加载中</el-button></div>
             <div class="ds-row"><el-button type="primary" size="large">large</el-button><el-button type="primary">default</el-button><el-button type="primary" size="small">small</el-button><el-button type="primary" round>圆角</el-button><el-button type="primary" circle><el-icon><Search /></el-icon></el-button><el-button-group><el-button type="primary"><el-icon><ArrowLeft /></el-icon>上一页</el-button><el-button type="primary">下一页<el-icon class="el-icon--right"><ArrowRight /></el-icon></el-button></el-button-group></div>` },
    { key: 'border', cat: 'basic', name: 'Border', cn: '边框', tags: [], note: '样式规范', tokens: ['--border-w', '--color-border-default', '--color-border-muted', '--radius-md', '--shadow-md'], usage: 'border: var(--border-w) solid var(--color-border-default);',
      demo: `<div class="ds-row"><div style="width: 96px; height: 56px; border: var(--border-w) solid var(--color-border-default); border-radius: var(--radius-md); background: var(--color-bg-surface);"></div><div style="width: 96px; height: 56px; border: var(--border-w) solid var(--color-border-muted); border-radius: var(--radius-lg); background: var(--color-bg-surface);"></div><div style="width: 96px; height: 56px; border: var(--border-w-thick) dashed var(--color-border-default); border-radius: var(--radius-md); background: var(--color-bg-surface);"></div><div style="width: 96px; height: 56px; border-radius: var(--radius-lg); background: var(--color-bg-surface); box-shadow: var(--shadow-sm);"></div><div style="width: 96px; height: 56px; border-radius: var(--radius-lg); background: var(--color-bg-surface); box-shadow: var(--shadow-md);"></div><div style="width: 96px; height: 56px; border-radius: var(--radius-lg); background: var(--color-bg-surface); box-shadow: var(--shadow-lg);"></div></div>` },
    { key: 'color', cat: 'basic', name: 'Color', cn: '色彩', tags: [], note: '样式规范', tokens: ['--color-primary', '--color-success', '--color-warning', '--color-danger', '--color-info', '--color-text-*', '--color-bg-*'], usage: 'color: var(--color-text-secondary); background: var(--color-bg-surface);',
      demo: `<div class="ds-row"><div v-for="c in ['primary','success','warning','danger','info']" :key="c" style="display: flex; flex-direction: column; gap: 4px; width: 88px;"><div style="height: 40px; border-radius: var(--radius-md);" :style="{ background: 'var(--color-' + c + ')' }"></div><div style="height: 16px; border-radius: 2px;" :style="{ background: 'var(--el-color-' + c + '-light-3)' }"></div><div style="height: 16px; border-radius: 2px;" :style="{ background: 'var(--el-color-' + c + '-light-7)' }"></div><div style="height: 16px; border-radius: 2px;" :style="{ background: 'var(--el-color-' + c + '-light-9)' }"></div><small class="ds-mono">{{ c }}</small></div></div><div class="ds-stage-note">light-3/7/9 由 color-mix 从主色派生，无需单独维护。</div>` },
    { key: 'container', cat: 'basic', name: 'Container', cn: '布局容器', tags: [], note: '由 UiShell 封装', tokens: ['--layout-header-h', '--layout-sidebar-w', '--color-bg-page', '--color-bg-surface'], usage: '<el-container><el-header/><el-container><el-aside/><el-main/></el-container></el-container>',
      demo: `<el-container style="height: 140px; border: var(--border-w) solid var(--color-border-muted); border-radius: var(--radius-md); overflow: hidden;"><el-header style="height: var(--layout-header-h); background: var(--el-color-primary-light-9); color: var(--color-primary); display: flex; align-items: center; font-size: 12px;">Header · --layout-header-h</el-header><el-container><el-aside style="width: var(--layout-sidebar-w-collapsed); background: var(--el-color-primary-light-8); display: flex; align-items: center; justify-content: center; font-size: 11px; color: var(--color-primary);">Aside</el-aside><el-main style="display: flex; align-items: center; justify-content: center; font-size: 12px; color: var(--color-text-muted); background: var(--color-bg-page);">Main · --layout-content-max</el-main></el-container></el-container>` },
    { key: 'icon', cat: 'basic', name: 'Icon', cn: '图标', tags: ['el-icon'], tokens: ['--color-icon-default', '--color-icon-muted', '--color-primary'], usage: '<el-icon :size="18"><Search /></el-icon>',
      demo: `<div class="ds-row" style="font-size: 20px; color: var(--color-icon-default); gap: var(--space-4);"><el-icon><Search /></el-icon><el-icon><Edit /></el-icon><el-icon><Delete /></el-icon><el-icon><Plus /></el-icon><el-icon><Setting /></el-icon><el-icon><Bell /></el-icon><el-icon><Document /></el-icon><el-icon><User /></el-icon><el-icon style="color: var(--color-primary);"><Check /></el-icon><el-icon style="color: var(--color-danger);"><Close /></el-icon><el-icon style="color: var(--color-icon-muted);"><Clock /></el-icon><el-icon :size="28"><Star /></el-icon></div>` },
    { key: 'layout', cat: 'basic', name: 'Layout', cn: '栅格', tags: [], note: '用 .l-grid 替代', tokens: ['--grid-cols', '--grid-gap'], usage: '<div class="l-grid l-grid--cols-3">…</div>',
      demo: `<el-row :gutter="12"><el-col :span="8"><div class="ds-block">span 8</div></el-col><el-col :span="8"><div class="ds-block">span 8</div></el-col><el-col :span="8"><div class="ds-block">span 8</div></el-col></el-row><el-row :gutter="12"><el-col :span="6"><div class="ds-block">6</div></el-col><el-col :span="12"><div class="ds-block">12</div></el-col><el-col :span="6"><div class="ds-block">6</div></el-col></el-row><div class="ds-stage-note">第三层禁止直接用 el-row / el-col，改用第一层 .l-grid（同一套 --grid-* token）。</div>` },
    { key: 'link', cat: 'basic', name: 'Link', cn: '链接', tokens: ['--color-primary', '--color-primary-hover', '--color-text-*'], usage: '<el-link type="primary">链接</el-link>',
      demo: `<div class="ds-row" style="gap: var(--space-5);"><el-link>默认</el-link><el-link type="primary">主要</el-link><el-link type="success">成功</el-link><el-link type="warning">警告</el-link><el-link type="danger">危险</el-link><el-link type="info">信息</el-link><el-link disabled>禁用</el-link><el-link type="primary" :underline="false">无下划线</el-link></div>` },
    { key: 'text', cat: 'basic', name: 'Text', cn: '文本', tokens: ['--font-size-*', '--color-text-*', '--line-height-body'], usage: '<el-text type="info" size="small">说明</el-text>',
      demo: `<div class="ds-row" style="gap: var(--space-5); align-items: baseline;"><el-text>默认</el-text><el-text type="primary">主要</el-text><el-text type="success">成功</el-text><el-text type="warning">警告</el-text><el-text type="danger">危险</el-text><el-text type="info">信息</el-text><el-text size="large">large</el-text><el-text size="small">small</el-text><el-text tag="b">粗体</el-text><el-text truncated style="width: 120px;">很长很长的一段会被截断的文本内容</el-text></div>` },
    { key: 'scrollbar', cat: 'basic', name: 'Scrollbar', cn: '滚动条', wide: true, tokens: ['--color-border-default', '--radius-full'], usage: '<el-scrollbar height="200px">…</el-scrollbar>',
      demo: `<div class="l-grid l-grid--cols-2"><el-scrollbar height="120px"><div v-for="i in 12" :key="i" style="padding: 8px 12px; margin: 0 0 6px; border-radius: var(--radius-md); background: var(--el-color-primary-light-9); color: var(--color-primary); font-size: 12px;">纵向滚动项 {{ i }}</div></el-scrollbar><el-scrollbar><div class="l-cluster" style="flex-wrap: nowrap; width: max-content;"><div v-for="i in 10" :key="i" style="width: 120px; height: 120px; border-radius: var(--radius-md); background: var(--el-color-primary-light-8); color: var(--color-primary); font-size: 12px; display: grid; place-items: center;">横向 {{ i }}</div></div></el-scrollbar></div><div class="ds-stage-note">规则 R-043：所有滚动区域（含 UiShell 侧栏 / 主区、本页侧栏 / 主区）都用 el-scrollbar，禁止 overflow: auto / scroll。</div>` },
    { key: 'space', cat: 'basic', name: 'Space', cn: '间距', tags: [], note: '用 .l-cluster 替代', tokens: ['--space-component-gap'], usage: '<div class="l-cluster">…</div>',
      demo: `<el-space wrap><el-button v-for="i in 5" :key="i">按钮 {{ i }}</el-button></el-space><el-space direction="vertical" alignment="start"><el-tag>纵向</el-tag><el-tag type="success">纵向</el-tag></el-space><div class="ds-stage-note">第三层用第一层 .l-cluster / .l-stack，间距由 token 决定。</div>` },
    { key: 'splitter', cat: 'basic', name: 'Splitter', cn: '分隔面板', tokens: ['--color-border-muted', '--color-bg-surface'], usage: '<el-splitter><el-splitter-panel/><el-splitter-panel/></el-splitter>',
      demo: `<el-splitter style="height: 120px; border: var(--border-w) solid var(--color-border-muted); border-radius: var(--radius-md);"><el-splitter-panel size="40%"><div style="height: 100%; display: flex; align-items: center; justify-content: center; font-size: 12px; color: var(--color-text-muted);">左 · 可拖拽</div></el-splitter-panel><el-splitter-panel><div style="height: 100%; display: flex; align-items: center; justify-content: center; font-size: 12px; color: var(--color-text-muted);">右</div></el-splitter-panel></el-splitter>` },

    /* ---------------- Config ---------------- */
    { key: 'config-provider', cat: 'config', name: 'Config Provider', cn: '全局配置', tags: [], note: '入口统一设置', tokens: ['--font-size-body', '--layout-form-label-w'], usage: '<el-config-provider :locale="zhCn" size="default">…</el-config-provider>',
      demo: `<el-config-provider size="small"><div class="ds-row"><el-button type="primary">small 按钮</el-button><el-input placeholder="small 输入框" style="width: 160px;" /><el-tag>small 标签</el-tag></div></el-config-provider><el-config-provider size="large"><div class="ds-row"><el-button type="primary">large 按钮</el-button><el-input placeholder="large 输入框" style="width: 160px;" /></div></el-config-provider>` },

    /* ---------------- Form ---------------- */
    { key: 'autocomplete', cat: 'form', name: 'Autocomplete', cn: '自动补全', tokens: ['--color-border-default', '--color-bg-overlay', '--shadow-md', '--radius-md'], usage: '<el-autocomplete v-model="v" :fetch-suggestions="fn" />', init: '',
      demo: `<el-autocomplete v-model="v" :fetch-suggestions="(q, cb) => cb(list.filter(x => x.includes(q)).map(value => ({ value })))" placeholder="输入「示例」试试" style="width: 260px;" />` },
    { key: 'cascader', cat: 'form', name: 'Cascader', cn: '级联选择', tokens: ['--color-border-default', '--color-primary', '--color-bg-overlay'], usage: '<el-cascader v-model="v" :options="opts" />',
      demo: `<div class="ds-row"><el-cascader v-model="v" :options="cascade" placeholder="选择地区" style="width: 260px;" /><el-cascader-panel :options="cascade" style="height: 140px;" /></div>` },
    { key: 'checkbox', cat: 'form', name: 'Checkbox', cn: '多选框', tokens: ['--color-primary', '--color-border-default', '--radius-sm'], usage: '<el-checkbox-group v-model="v"><el-checkbox value="a">A</el-checkbox></el-checkbox-group>', init: ['web'],
      demo: `<el-checkbox-group v-model="v"><el-checkbox value="web">Web</el-checkbox><el-checkbox value="app">App</el-checkbox><el-checkbox value="wechat">微信</el-checkbox><el-checkbox value="x" disabled>禁用</el-checkbox></el-checkbox-group><el-checkbox-group v-model="v"><el-checkbox-button value="web">Web</el-checkbox-button><el-checkbox-button value="app">App</el-checkbox-button><el-checkbox-button value="wechat">微信</el-checkbox-button></el-checkbox-group>` },
    { key: 'color-picker', cat: 'form', name: 'Color Picker', cn: '取色器', tokens: ['--color-border-default', '--radius-md'], usage: '<el-color-picker v-model="v" />', init: '#409eff',
      demo: `<div class="ds-row"><el-color-picker v-model="v" /><el-color-picker v-model="v" show-alpha /><el-color-picker v-model="v" size="small" /><el-color-picker v-model="v" disabled /></div>` },
    { key: 'date-picker', cat: 'form', name: 'Date Picker', cn: '日期选择', tokens: ['--color-primary', '--color-border-default', '--color-bg-overlay', '--shadow-md'], usage: '<el-date-picker v-model="v" type="date" />',
      demo: `<div class="ds-row"><el-date-picker v-model="v" type="date" placeholder="选择日期" /><el-date-picker v-model="v2" type="daterange" range-separator="至" start-placeholder="开始" end-placeholder="结束" /></div>` },
    { key: 'datetime-picker', cat: 'form', name: 'DateTime Picker', cn: '日期时间', tags: ['el-date-picker'], tokens: ['--color-primary', '--color-border-default'], usage: '<el-date-picker v-model="v" type="datetime" />',
      demo: `<div class="ds-row"><el-date-picker v-model="v" type="datetime" placeholder="选择日期时间" /><el-date-picker v-model="v2" type="month" placeholder="选择月份" /></div>` },
    { key: 'form', cat: 'form', name: 'Form', cn: '表单', wide: true, tokens: ['--layout-form-label-w', '--space-component-title', '--color-danger', '--font-size-caption'], usage: '<el-form class="l-form" :model="m" :rules="r"><el-form-item label="名称" prop="name"><el-input v-model="m.name" /></el-form-item></el-form>', init: { name: '', status: '', amount: 1200, date: '', remark: '', enabled: true },
      demo: `<el-form class="l-form" :model="v" label-position="right" :rules="{ name: [{ required: true, message: '必填', trigger: 'blur' }] }"><div class="l-grid l-grid--cols-2"><el-form-item label="客户名称" prop="name"><el-input v-model="v.name" placeholder="请输入" clearable /></el-form-item><el-form-item label="金额"><el-input-number v-model="v.amount" :min="0" :step="100" /></el-form-item><el-form-item label="状态"><el-select v-model="v.status" placeholder="请选择"><el-option v-for="o in opts" :key="o.value" :label="o.label" :value="o.value" /></el-select></el-form-item><el-form-item label="交付日期"><el-date-picker v-model="v.date" type="date" placeholder="选择日期" /></el-form-item><el-form-item label="启用"><el-switch v-model="v.enabled" /></el-form-item><el-form-item label="备注"><el-input v-model="v.remark" type="textarea" :rows="2" /></el-form-item></div><el-form-item><div class="l-cluster"><el-button type="primary">提交</el-button><el-button>重置</el-button></div></el-form-item></el-form>` },
    { key: 'input', cat: 'form', name: 'Input', cn: '输入框', tokens: ['--color-border-default', '--color-text-placeholder', '--color-bg-muted', '--radius-md', '--layout-control-w'], usage: '<el-input v-model="v" placeholder="请输入" clearable />', init: '',
      demo: `<div class="ds-row"><el-input v-model="v" placeholder="请输入内容" clearable style="width: 200px;" /><el-input v-model="v" placeholder="禁用" disabled style="width: 160px;" /><el-input v-model="v" placeholder="带前缀" style="width: 200px;"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-input v-model="v" placeholder="密码" show-password style="width: 160px;" /></div><div class="ds-row"><el-input v-model="v" placeholder="带前置" style="width: 260px;"><template #prepend>https://</template><template #append>.com</template></el-input><el-input v-model="v" type="textarea" :rows="2" placeholder="多行" style="width: 260px;" /></div>` },
    { key: 'input-number', cat: 'form', name: 'Input Number', cn: '数字输入', tokens: ['--color-border-default', '--color-bg-muted', '--radius-md'], usage: '<el-input-number v-model="v" :min="0" />', init: 1200,
      demo: `<div class="ds-row"><el-input-number v-model="v" :min="0" :step="100" /><el-input-number v-model="v" controls-position="right" /><el-input-number v-model="v" size="small" /><el-input-number v-model="v" disabled /></div>` },
    { key: 'input-tag', cat: 'form', name: 'Input Tag', cn: '标签输入', tokens: ['--color-border-default', '--radius-sm', '--el-color-primary-light-9'], usage: '<el-input-tag v-model="v" />', init: ['标签一', '标签二'],
      demo: `<el-input-tag v-model="v" placeholder="回车添加" style="width: 320px;" />` },
    { key: 'mention', cat: 'form', name: 'Mention', cn: '提及', tokens: ['--color-border-default', '--color-bg-overlay', '--shadow-md'], usage: '<el-mention v-model="v" :options="opts" />', init: '',
      demo: `<el-mention v-model="v" :options="list.map(value => ({ value }))" placeholder="输入 @ 试试" style="width: 320px;" />` },
    { key: 'radio', cat: 'form', name: 'Radio', cn: '单选框', tokens: ['--color-primary', '--color-border-default'], usage: '<el-radio-group v-model="v"><el-radio value="a">A</el-radio></el-radio-group>', init: 'mid',
      demo: `<el-radio-group v-model="v"><el-radio value="low">低</el-radio><el-radio value="mid">中</el-radio><el-radio value="high">高</el-radio><el-radio value="x" disabled>禁用</el-radio></el-radio-group><el-radio-group v-model="v"><el-radio-button value="low">低</el-radio-button><el-radio-button value="mid">中</el-radio-button><el-radio-button value="high">高</el-radio-button></el-radio-group>` },
    { key: 'rate', cat: 'form', name: 'Rate', cn: '评分', tokens: ['--color-warning', '--color-border-default'], usage: '<el-rate v-model="v" />', init: 3.5,
      demo: `<div class="ds-row" style="gap: var(--space-6);"><el-rate v-model="v" allow-half /><el-rate v-model="v" show-score /><el-rate v-model="v" disabled /></div>` },
    { key: 'select', cat: 'form', name: 'Select', cn: '选择器', tokens: ['--color-border-default', '--color-primary', '--color-bg-overlay', '--shadow-md', '--layout-control-w'], usage: '<el-select v-model="v"><el-option label="A" value="a" /></el-select>',
      demo: `<div class="ds-row"><el-select v-model="v" placeholder="请选择" style="width: 200px;"><el-option v-for="o in opts" :key="o.value" :label="o.label" :value="o.value" /></el-select><el-select v-model="v2" multiple placeholder="多选" style="width: 240px;"><el-option v-for="o in opts" :key="o.value" :label="o.label" :value="o.value" /></el-select><el-select v-model="v" disabled placeholder="禁用" style="width: 120px;"><el-option label="A" value="a" /></el-select></div>` },
    { key: 'select-v2', cat: 'form', name: 'Virtualized Select', cn: '虚拟化选择器', tokens: ['--color-border-default', '--color-bg-overlay'], usage: '<el-select-v2 v-model="v" :options="opts" />',
      demo: `<el-select-v2 v-model="v" :options="big.map(x => ({ value: x.id, label: x.customer }))" placeholder="200 条虚拟滚动" style="width: 260px;" />` },
    { key: 'slider', cat: 'form', name: 'Slider', cn: '滑块', tokens: ['--color-primary', '--color-bg-muted', '--radius-full'], usage: '<el-slider v-model="v" />', init: 40,
      demo: `<div style="padding: 0 var(--space-3); display: flex; flex-direction: column; gap: var(--space-4);"><el-slider v-model="v" /><el-slider v-model="v" show-input /><el-slider v-model="v" :step="10" show-stops /></div>` },
    { key: 'switch', cat: 'form', name: 'Switch', cn: '开关', tokens: ['--color-primary', '--color-border-default', '--radius-full'], usage: '<el-switch v-model="v" />', init: true,
      demo: `<div class="ds-row" style="gap: var(--space-5);"><el-switch v-model="v" /><el-switch v-model="v" active-text="开" inactive-text="关" /><el-switch v-model="v" inline-prompt active-text="是" inactive-text="否" /><el-switch v-model="v" size="small" /><el-switch v-model="v" disabled /></div>` },
    { key: 'time-picker', cat: 'form', name: 'Time Picker', cn: '时间选择', tokens: ['--color-primary', '--color-border-default'], usage: '<el-time-picker v-model="v" />',
      demo: `<div class="ds-row"><el-time-picker v-model="v" placeholder="选择时间" /><el-time-picker v-model="v2" is-range range-separator="至" start-placeholder="开始" end-placeholder="结束" /></div>` },
    { key: 'time-select', cat: 'form', name: 'Time Select', cn: '时间选择（固定）', tokens: ['--color-primary', '--color-border-default'], usage: '<el-time-select v-model="v" start="08:30" step="00:15" end="18:30" />',
      demo: `<el-time-select v-model="v" start="08:30" step="00:30" end="18:30" placeholder="选择时段" />` },
    { key: 'transfer', cat: 'form', name: 'Transfer', cn: '穿梭框', wide: true, tokens: ['--color-border-default', '--color-bg-subtle', '--color-primary'], usage: '<el-transfer v-model="v" :data="data" />', init: [1, 3],
      demo: `<el-transfer v-model="v" :data="transfer" :titles="['候选', '已选']" />` },
    { key: 'tree-select', cat: 'form', name: 'TreeSelect', cn: '树形选择', tokens: ['--color-border-default', '--color-bg-overlay', '--color-primary'], usage: '<el-tree-select v-model="v" :data="tree" />',
      demo: `<div class="ds-row"><el-tree-select v-model="v" :data="tree" node-key="id" placeholder="选择节点" style="width: 240px;" /><el-tree-select v-model="v2" :data="tree" node-key="id" multiple show-checkbox placeholder="多选" style="width: 260px;" /></div>` },
    { key: 'upload', cat: 'form', name: 'Upload', cn: '上传', tokens: ['--color-border-default', '--color-primary', '--radius-md', '--color-bg-subtle'], usage: '<el-upload action="#" :auto-upload="false"><el-button>选择文件</el-button></el-upload>',
      demo: `<div class="ds-row" style="align-items: flex-start; gap: var(--space-6);"><el-upload action="#" :auto-upload="false"><el-button type="primary">选择文件</el-button><template #tip><div class="ds-stage-note">jpg / png，不超过 2MB</div></template></el-upload><el-upload action="#" :auto-upload="false" drag style="width: 280px;"><el-icon style="font-size: 40px; color: var(--color-icon-muted);"><UploadFilled /></el-icon><div style="font-size: 12px; color: var(--color-text-secondary);">拖拽到此处或 <em style="color: var(--color-primary);">点击上传</em></div></el-upload></div>` },

    /* ---------------- Data ---------------- */
    { key: 'avatar', cat: 'data', name: 'Avatar', cn: '头像', tokens: ['--color-bg-muted', '--color-text-secondary', '--radius-full'], usage: '<el-avatar>用</el-avatar>',
      demo: `<div class="ds-row" style="gap: var(--space-4);"><el-avatar>用</el-avatar><el-avatar :size="48" style="background: var(--color-primary);">袁</el-avatar><el-avatar shape="square">方</el-avatar><el-avatar :size="32"><el-icon><User /></el-icon></el-avatar><el-avatar :size="24" shape="square"><el-icon><User /></el-icon></el-avatar></div>` },
    { key: 'badge', cat: 'data', name: 'Badge', cn: '徽章', tokens: ['--color-danger', '--radius-full', '--font-size-caption'], usage: '<el-badge :value="12"><el-button>消息</el-button></el-badge>',
      demo: `<div class="ds-row" style="gap: var(--space-6);"><el-badge :value="12"><el-button>消息</el-button></el-badge><el-badge :value="120" :max="99"><el-button>上限</el-button></el-badge><el-badge is-dot><el-button>提醒</el-button></el-badge><el-badge value="new" type="primary"><el-button>类型</el-button></el-badge><el-badge :value="3" type="success"><el-button>成功</el-button></el-badge></div>` },
    { key: 'calendar', cat: 'data', name: 'Calendar', cn: '日历', wide: true, tokens: ['--color-primary', '--color-border-muted', '--color-bg-subtle'], usage: '<el-calendar v-model="v" />',
      demo: `<el-calendar v-model="v" style="--el-calendar-cell-width: 44px;" />` },
    { key: 'card', cat: 'data', name: 'Card', cn: '卡片', tags: [], note: '用 .l-module 替代', tokens: ['--color-bg-surface', '--color-border-muted', '--radius-lg', '--shadow-sm', '--space-module-pad'], usage: '<section class="l-module">…</section>',
      demo: `<div class="ds-row" style="align-items: stretch;"><el-card style="width: 240px;"><template #header>卡片标题</template><div style="font-size: 13px; color: var(--color-text-secondary);">el-card：header + body，阴影 hover 出现。</div></el-card><el-card shadow="always" style="width: 240px;"><div style="font-size: 13px; color: var(--color-text-secondary);">shadow=always</div></el-card><section class="l-module" style="width: 240px;"><div class="l-module-header"><h2>.l-module</h2></div><div style="font-size: 13px; color: var(--color-text-secondary);">第一层布局类，第三层用它。</div></section></div>` },
    { key: 'carousel', cat: 'data', name: 'Carousel', cn: '走马灯', tokens: ['--color-primary', '--color-bg-mask', '--radius-lg'], usage: '<el-carousel height="160px"><el-carousel-item v-for="i in 4" :key="i">…</el-carousel-item></el-carousel>',
      demo: `<el-carousel height="140px" style="border-radius: var(--radius-lg); overflow: hidden;"><el-carousel-item v-for="i in 4" :key="i"><div style="height: 100%; display: flex; align-items: center; justify-content: center; font-size: 20px; color: var(--color-primary);" :style="{ background: i % 2 ? 'var(--el-color-primary-light-9)' : 'var(--el-color-primary-light-8)' }">第 {{ i }} 屏</div></el-carousel-item></el-carousel>` },
    { key: 'collapse', cat: 'data', name: 'Collapse', cn: '折叠面板', tokens: ['--color-border-muted', '--color-text-default', '--font-size-body'], usage: '<el-collapse v-model="v"><el-collapse-item title="A" name="a">…</el-collapse-item></el-collapse>', init: ['a'],
      demo: `<el-collapse v-model="v"><el-collapse-item title="一致性 Consistency" name="a"><div style="font-size: 13px; color: var(--color-text-secondary);">与现实生活一致：与现实生活的流程、逻辑保持一致，遵循用户习惯的语言和概念。</div></el-collapse-item><el-collapse-item title="反馈 Feedback" name="b"><div style="font-size: 13px; color: var(--color-text-secondary);">控制反馈：通过界面样式和交互动效让用户可以清晰的感知自己的操作。</div></el-collapse-item><el-collapse-item title="效率 Efficiency" name="c" disabled></el-collapse-item></el-collapse>` },
    { key: 'countdown', cat: 'data', name: 'Countdown', cn: '倒计时', tokens: ['--font-size-page-title', '--color-text-default'], usage: '<el-countdown :value="Date.now() + 3600e3" />',
      demo: `<div class="ds-row" style="gap: var(--space-8);"><el-countdown title="距截止" :value="Date.now() + 1000 * 60 * 60 * 26" /><el-countdown title="剩余" format="HH:mm:ss" :value="Date.now() + 1000 * 60 * 7" /></div>` },
    { key: 'descriptions', cat: 'data', name: 'Descriptions', cn: '描述列表', wide: true, tokens: ['--color-bg-subtle', '--color-border-muted', '--color-text-secondary'], usage: '<el-descriptions :column="3" border><el-descriptions-item label="客户">…</el-descriptions-item></el-descriptions>',
      demo: `<el-descriptions title="订单信息" :column="3" border><el-descriptions-item label="单号">SO-20260901-001</el-descriptions-item><el-descriptions-item label="客户">成都示例科技</el-descriptions-item><el-descriptions-item label="金额">12,800</el-descriptions-item><el-descriptions-item label="状态"><el-tag size="small" type="warning">待处理</el-tag></el-descriptions-item><el-descriptions-item label="创建时间">2026-09-01 10:24</el-descriptions-item><el-descriptions-item label="备注">常规订单</el-descriptions-item></el-descriptions>` },
    { key: 'empty', cat: 'data', name: 'Empty', cn: '空状态', tokens: ['--color-text-muted', '--color-bg-muted'], usage: '<ui-state state="empty" />（内部使用 el-empty）',
      demo: `<div class="ds-row" style="gap: var(--space-8);"><el-empty description="暂无数据" :image-size="64" /><el-empty :image-size="64"><template #description><span>自定义描述</span></template><el-button type="primary" size="small">新建</el-button></el-empty></div>` },
    { key: 'image', cat: 'data', name: 'Image', cn: '图片', tokens: ['--color-bg-muted', '--radius-md', '--color-text-placeholder'], usage: '<el-image :src="url" fit="cover" :preview-src-list="[url]" />',
      demo: `<div class="ds-row"><el-image style="width: 120px; height: 80px; border-radius: var(--radius-md);" src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='120' height='80'><rect width='120' height='80' fill='%23409eff'/></svg>" fit="cover" /><el-image style="width: 120px; height: 80px; border-radius: var(--radius-md);" src="https://invalid.example/x.png"><template #error><div style="height: 100%; display: flex; align-items: center; justify-content: center; background: var(--color-bg-muted); color: var(--color-text-placeholder); font-size: 12px;">加载失败</div></template></el-image><el-image style="width: 120px; height: 80px; border-radius: var(--radius-md);"><template #placeholder><div style="height: 100%; background: var(--color-bg-muted);"></div></template></el-image></div>` },
    { key: 'infinite-scroll', cat: 'data', name: 'Infinite Scroll', cn: '无限滚动', tags: [], note: '指令', tokens: ['--color-bg-subtle', '--space-component-gap'], usage: '<ul v-infinite-scroll="load">…</ul>',
      demo: `<el-scrollbar height="120px"><ul v-infinite-scroll="() => { n = Math.min(n + 3, 30) }" class="l-stack l-stack--tight" style="margin: 0; padding: 0; list-style: none;"><li v-for="i in n" :key="i" style="padding: 8px 12px; border-radius: var(--radius-md); background: var(--el-color-primary-light-9); color: var(--color-primary); font-size: 12px;">滚动加载 {{ i }}</li></ul></el-scrollbar><div class="ds-stage-note">滚动容器是 el-scrollbar（R-043），指令自动找到它。</div>` },
    { key: 'pagination', cat: 'data', name: 'Pagination', cn: '分页', wide: true, tokens: ['--color-primary', '--color-bg-muted', '--radius-sm', '--font-size-body'], usage: '<el-pagination layout="total, prev, pager, next, sizes" :total="total" v-model:current-page="page" v-model:page-size="pageSize" />（含 sizes 时必须 v-model:page-size，否则不渲染）',
      demo: `<div class="l-stack l-stack--tight"><el-pagination layout="total, prev, pager, next, sizes" :total="128" v-model:current-page="page" v-model:page-size="pageSize" :page-sizes="[10, 20, 50]" /><el-pagination background layout="prev, pager, next" :total="128" /><el-pagination layout="prev, pager, next, jumper" :total="1000" small /></div>` },
    { key: 'progress', cat: 'data', name: 'Progress', cn: '进度条', tokens: ['--color-primary', '--color-success', '--color-bg-muted', '--radius-full'], usage: '<el-progress :percentage="60" />',
      demo: `<div class="l-stack l-stack--tight"><el-progress :percentage="40" /><el-progress :percentage="100" status="success" /><el-progress :percentage="70" status="warning" /><el-progress :percentage="30" status="exception" /><div class="ds-row" style="gap: var(--space-6);"><el-progress type="circle" :percentage="65" :width="64" /><el-progress type="dashboard" :percentage="80" :width="64" /><el-progress :percentage="50" :stroke-width="14" text-inside style="width: 200px;" /></div></div>` },
    { key: 'result', cat: 'data', name: 'Result', cn: '结果', tokens: ['--color-success', '--color-warning', '--color-danger', '--color-text-secondary'], usage: '<el-result icon="success" title="提交成功" />',
      demo: `<div class="ds-row" style="gap: var(--space-8); justify-content: space-around;"><el-result icon="success" title="成功" sub-title="订单已提交" style="padding: 0;" /><el-result icon="warning" title="警告" style="padding: 0;" /><el-result icon="error" title="错误" style="padding: 0;" /><el-result icon="info" title="信息" style="padding: 0;" /></div>` },
    { key: 'skeleton', cat: 'data', name: 'Skeleton', cn: '骨架屏', tokens: ['--color-bg-muted', '--radius-md'], usage: '<ui-state state="loading" />（内部使用 el-skeleton）',
      demo: `<el-skeleton :rows="3" animated /><el-skeleton style="width: 240px;" animated><template #template><el-skeleton-item variant="image" style="width: 240px; height: 100px;" /><div style="padding: 12px 0;"><el-skeleton-item variant="h3" style="width: 50%;" /><el-skeleton-item variant="text" style="margin-top: 8px;" /></div></template></el-skeleton>` },
    { key: 'table', cat: 'data', name: 'Table', cn: '表格', wide: true, tokens: ['--color-bg-subtle', '--color-border-muted', '--color-text-secondary', '--font-size-body', '--space-module-title'], usage: '<el-table :data="rows" stripe><el-table-column prop="no" label="单号" /></el-table>',
      demo: `<el-table :data="rows" stripe><el-table-column type="selection" width="44" /><el-table-column prop="no" label="单号" width="160" /><el-table-column prop="customer" label="客户" min-width="160" show-overflow-tooltip /><el-table-column prop="amount" label="金额" width="120" align="right" /><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag size="small" :type="{ pending: 'warning', done: 'success', cancelled: 'info' }[row.status]">{{ opts.find(o => o.value === row.status).label }}</el-tag></template></el-table-column><el-table-column prop="date" label="日期" width="120" sortable /><el-table-column label="操作" width="120" fixed="right"><template #default><el-button text type="primary" size="small">查看</el-button><el-button text type="danger" size="small">删除</el-button></template></el-table-column></el-table>` },
    { key: 'table-v2', cat: 'data', name: 'Virtualized Table', cn: '虚拟化表格', wide: true, tokens: ['--color-bg-subtle', '--color-border-muted'], usage: '<el-table-v2 :columns="cols" :data="rows" :width="800" :height="240" />',
      demo: `<el-table-v2 :columns="cols" :data="big" :width="960" :height="200" fixed /><div class="ds-stage-note">200 行虚拟滚动；列宽为固定像素是该组件的 API 约束，不受 token 管理。</div>` },
    { key: 'tag', cat: 'data', name: 'Tag', cn: '标签', tokens: ['--color-primary', '--color-success', '--color-warning', '--color-danger', '--radius-sm', '--font-size-caption'], usage: '<el-tag type="success" size="small">已完成</el-tag>',
      demo: `<div class="ds-row"><el-tag>标签</el-tag><el-tag type="success">成功</el-tag><el-tag type="warning">警告</el-tag><el-tag type="danger">危险</el-tag><el-tag type="info">信息</el-tag></div><div class="ds-row"><el-tag effect="dark">dark</el-tag><el-tag effect="dark" type="success">dark</el-tag><el-tag effect="plain">plain</el-tag><el-tag effect="plain" type="danger">plain</el-tag><el-tag closable>可关闭</el-tag><el-tag round>圆角</el-tag><el-tag size="small">small</el-tag><el-tag size="large">large</el-tag></div>` },
    { key: 'check-tag', cat: 'data', name: 'Check Tag', cn: '可选标签', tokens: ['--color-primary', '--radius-sm'], usage: '<el-check-tag :checked="v" @change="v = !v">选中</el-check-tag>', init: true,
      demo: `<div class="ds-row"><el-check-tag :checked="v" @change="v = !v">可选中</el-check-tag><el-check-tag :checked="!v" @change="v = !v">另一个</el-check-tag><el-check-tag checked type="success">success</el-check-tag><el-check-tag checked type="danger">danger</el-check-tag></div>` },
    { key: 'timeline', cat: 'data', name: 'Timeline', cn: '时间线', tokens: ['--color-primary', '--color-border-default', '--color-text-muted'], usage: '<el-timeline><el-timeline-item timestamp="2026-09-01">…</el-timeline-item></el-timeline>',
      demo: `<el-timeline style="padding-left: 4px;"><el-timeline-item timestamp="2026-09-01 10:24" type="primary">订单创建</el-timeline-item><el-timeline-item timestamp="2026-09-01 14:02" type="success">审核通过</el-timeline-item><el-timeline-item timestamp="2026-09-02 09:10">发货</el-timeline-item></el-timeline>` },
    { key: 'tour', cat: 'data', name: 'Tour', cn: '漫游式引导', tokens: ['--color-bg-overlay', '--color-bg-mask', '--shadow-lg', '--radius-lg'], usage: '<el-tour v-model="open"><el-tour-step target="#x" title="…" /></el-tour>',
      demo: `<div class="ds-row"><el-button ref="t1" type="primary" @click="open = true">开始引导</el-button><el-button ref="t2">第二步目标</el-button></div><el-tour v-model="open"><el-tour-step :target="() => $refs.t1?.$el" title="第一步" description="点击这里开始。" /><el-tour-step :target="() => $refs.t2?.$el" title="第二步" description="然后看这里。" /></el-tour>` },
    { key: 'tree', cat: 'data', name: 'Tree', cn: '树形控件', tokens: ['--color-primary', '--color-bg-subtle', '--font-size-body'], usage: '<el-tree :data="tree" node-key="id" default-expand-all />',
      demo: `<div class="ds-row" style="align-items: flex-start; gap: var(--space-8);"><el-tree :data="tree" node-key="id" default-expand-all highlight-current /><el-tree :data="tree" node-key="id" show-checkbox default-expand-all /></div>` },
    { key: 'tree-v2', cat: 'data', name: 'Virtualized Tree', cn: '虚拟化树', tokens: ['--color-primary', '--color-bg-subtle'], usage: '<el-tree-v2 :data="tree" :props="props" :height="200" />',
      demo: `<el-tree-v2 :data="big.slice(0, 60).map(x => ({ id: x.id, label: x.customer }))" :props="{ value: 'id', label: 'label', children: 'children' }" :height="140" />` },
    { key: 'statistic', cat: 'data', name: 'Statistic', cn: '统计数值', tokens: ['--font-size-page-title', '--color-text-default', '--color-text-muted'], usage: '<el-statistic title="本月订单" :value="1280" />',
      demo: `<div class="ds-row" style="gap: var(--space-10);"><el-statistic title="本月订单" :value="1280" /><el-statistic title="成交金额" :value="2683400" prefix="¥" /><el-statistic title="转化率" :value="36.8" suffix="%" :precision="1" /></div>` },
    { key: 'segmented', cat: 'data', name: 'Segmented', cn: '分段控制器', tokens: ['--color-bg-muted', '--color-bg-surface', '--radius-md', '--shadow-sm'], usage: '<el-segmented v-model="v" :options="[\'日\',\'周\',\'月\']" />', init: '周',
      demo: `<div class="ds-row" style="gap: var(--space-6);"><el-segmented v-model="v" :options="['日', '周', '月', '年']" /><el-segmented v-model="v" :options="['日', '周', '月']" size="small" /><el-segmented v-model="v" :options="['日', '周', '月']" block style="width: 240px;" /></div>` },

    /* ---------------- Navigation ---------------- */
    { key: 'affix', cat: 'nav', name: 'Affix', cn: '固钉', tokens: ['--z-header', '--color-bg-surface', '--shadow-sm'], usage: '<el-affix :offset="80"><el-button>固定</el-button></el-affix>',
      demo: `<el-affix target=".ds-scroll .el-scrollbar__wrap" :offset="0"><el-button type="primary" plain size="small">滚动主区时我会固定在顶部</el-button></el-affix><div class="ds-stage-note">target 指向 UiShell / 展示页的 ElScrollbar 滚动容器（.el-scrollbar__wrap），因为 window 不滚动。</div>` },
    { key: 'anchor', cat: 'nav', name: 'Anchor', cn: '锚点', tokens: ['--color-primary', '--color-border-muted', '--font-size-caption'], usage: '<el-anchor><el-anchor-link href="#a" title="A" /></el-anchor>',
      demo: `<div class="ds-row" style="align-items: flex-start; gap: var(--space-8);"><el-anchor :offset="72" :bound="0"><el-anchor-link href="#cat-basic" title="Basic 基础" /><el-anchor-link href="#cat-form" title="Form 表单" /><el-anchor-link href="#cat-data" title="Data 数据展示" /></el-anchor><el-anchor direction="horizontal" :offset="72"><el-anchor-link href="#cat-nav" title="Navigation" /><el-anchor-link href="#cat-feedback" title="Feedback" /></el-anchor></div><div class="ds-stage-note">本页左侧分组锚点即同一模式的自实现。</div>` },
    { key: 'backtop', cat: 'nav', name: 'Backtop', cn: '回到顶部', tokens: ['--color-primary', '--color-bg-surface', '--shadow-md', '--radius-full'], usage: '<el-backtop :right="40" :bottom="40" />',
      demo: `<div class="ds-stage-note">主区滚动超过 200px 后右下角出现回到顶部按钮（target 为 ElScrollbar 的 wrap）。</div><el-backtop target=".ds-scroll .el-scrollbar__wrap" :right="40" :bottom="40" :visibility-height="200" />` },
    { key: 'breadcrumb', cat: 'nav', name: 'Breadcrumb', cn: '面包屑', tokens: ['--color-text-secondary', '--color-text-muted', '--font-size-body'], usage: '<el-breadcrumb separator="/"><el-breadcrumb-item>首页</el-breadcrumb-item></el-breadcrumb>',
      demo: `<el-breadcrumb separator="/"><el-breadcrumb-item>首页</el-breadcrumb-item><el-breadcrumb-item>订单管理</el-breadcrumb-item><el-breadcrumb-item>订单详情</el-breadcrumb-item></el-breadcrumb><el-breadcrumb separator=">"><el-breadcrumb-item>首页</el-breadcrumb-item><el-breadcrumb-item>客户管理</el-breadcrumb-item></el-breadcrumb>` },
    { key: 'dropdown', cat: 'nav', name: 'Dropdown', cn: '下拉菜单', tokens: ['--color-bg-overlay', '--shadow-md', '--radius-md', '--color-bg-subtle'], usage: '<el-dropdown><el-button>更多</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item>A</el-dropdown-item></el-dropdown-menu></template></el-dropdown>',
      demo: `<div class="ds-row" style="gap: var(--space-5);"><el-dropdown><el-button>更多操作<el-icon class="el-icon--right"><ArrowDown /></el-icon></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item>查看</el-dropdown-item><el-dropdown-item>编辑</el-dropdown-item><el-dropdown-item divided disabled>禁用</el-dropdown-item><el-dropdown-item divided style="color: var(--color-danger);">删除</el-dropdown-item></el-dropdown-menu></template></el-dropdown><el-dropdown split-button type="primary">主操作<template #dropdown><el-dropdown-menu><el-dropdown-item>选项一</el-dropdown-item><el-dropdown-item>选项二</el-dropdown-item></el-dropdown-menu></template></el-dropdown><el-dropdown trigger="click"><el-button link type="primary">点击触发</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item>选项</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div>` },
    { key: 'menu', cat: 'nav', name: 'Menu', cn: '菜单', tags: ['el-menu'], note: '仅 UiShell 内部使用', wide: true, tokens: ['--color-primary', '--color-bg-surface', '--color-text-default', '--layout-sidebar-w'], usage: '仅 UiShell 内部使用；第三层通过 UiShell 的 menu prop 传入',
      demo: `<div class="ds-row" style="align-items: flex-start; gap: var(--space-6);"><el-menu default-active="1-1" style="width: 220px; border-radius: var(--radius-md); border: var(--border-w) solid var(--color-border-muted);"><el-sub-menu index="1"><template #title><el-icon><Document /></el-icon><span>订单管理</span></template><el-menu-item index="1-1">订单列表</el-menu-item><el-menu-item index="1-2">退货处理</el-menu-item></el-sub-menu><el-menu-item index="2"><el-icon><User /></el-icon><span>客户管理</span></el-menu-item><el-menu-item index="3" disabled><el-icon><Setting /></el-icon><span>设置</span></el-menu-item></el-menu><el-menu mode="horizontal" default-active="1" :ellipsis="false" style="flex: 1; border-radius: var(--radius-md); border: var(--border-w) solid var(--color-border-muted);"><el-menu-item index="1">工作台</el-menu-item><el-menu-item index="2">订单</el-menu-item><el-sub-menu index="3"><template #title>报表</template><el-menu-item index="3-1">日报</el-menu-item><el-menu-item index="3-2">月报</el-menu-item></el-sub-menu></el-menu></div>` },
    { key: 'page-header', cat: 'nav', name: 'Page Header', cn: '页头', tags: [], note: '用 UiPageHeader 替代', tokens: ['--space-page-title', '--font-size-page-title'], usage: '<ui-page-header title="订单详情" subtitle="SO-001"></ui-page-header>',
      demo: `<el-page-header content="订单详情" title="返回" /><div class="ds-stage-note">第三层用自研 UiPageHeader（标题 + 副标题 + 操作区，间距取 --space-page-title）。</div>` },
    { key: 'steps', cat: 'nav', name: 'Steps', cn: '步骤条', wide: true, tokens: ['--color-primary', '--color-success', '--color-text-muted', '--color-border-default'], usage: '<el-steps :active="1" finish-status="success"><el-step title="提交" /></el-steps>',
      demo: `<div class="l-stack"><el-steps :active="step" finish-status="success" align-center><el-step v-for="s in steps" :key="s" :title="s" /></el-steps><el-steps :active="2" simple><el-step v-for="s in steps" :key="s" :title="s" /></el-steps><div class="ds-row"><el-button size="small" @click="step = (step + 1) % 5">下一步</el-button></div></div>` },
    { key: 'tabs', cat: 'nav', name: 'Tabs', cn: '标签页', tokens: ['--color-primary', '--color-border-muted', '--color-bg-subtle', '--font-size-body'], usage: '<el-tabs v-model="v"><el-tab-pane label="A" name="a">…</el-tab-pane></el-tabs>', init: 'a',
      demo: `<el-tabs v-model="v"><el-tab-pane label="基本信息" name="a"><div class="ds-stage-note">页签内容 A</div></el-tab-pane><el-tab-pane label="订单记录" name="b"><div class="ds-stage-note">页签内容 B</div></el-tab-pane><el-tab-pane label="操作日志" name="c" disabled></el-tab-pane></el-tabs><el-tabs v-model="v" type="card"><el-tab-pane label="卡片式" name="a"></el-tab-pane><el-tab-pane label="卡片式" name="b"></el-tab-pane></el-tabs><el-tabs v-model="v" type="border-card"><el-tab-pane label="带边框" name="a"><div class="ds-stage-note">border-card</div></el-tab-pane><el-tab-pane label="带边框" name="b"></el-tab-pane></el-tabs>` },

    /* ---------------- Feedback ---------------- */
    { key: 'alert', cat: 'feedback', name: 'Alert', cn: '提示', wide: true, tokens: ['--color-success', '--color-warning', '--color-danger', '--color-info', '--radius-md'], usage: '<el-alert title="操作成功" type="success" show-icon />',
      demo: `<div class="l-grid l-grid--cols-2 l-grid--tight"><el-alert title="成功提示" type="success" show-icon /><el-alert title="信息提示" type="info" show-icon /><el-alert title="警告提示" type="warning" show-icon /><el-alert title="错误提示" type="error" show-icon /><el-alert title="深色主题" type="success" effect="dark" /><el-alert title="带描述" type="warning" description="描述文字使用 --color-text-secondary。" show-icon :closable="false" /></div>` },
    { key: 'dialog', cat: 'feedback', name: 'Dialog', cn: '对话框', tokens: ['--color-bg-overlay', '--color-bg-mask', '--shadow-lg', '--radius-lg', '--z-dialog'], usage: '<el-dialog v-model="open" title="标题">…<template #footer>…</template></el-dialog>',
      demo: `<div class="ds-row"><el-button @click="open = true">打开 Dialog</el-button><el-button @click="open2 = true">居中 · 全屏</el-button></div><el-dialog v-model="open" title="对话框" width="480"><p style="font-size: 13px; color: var(--color-text-secondary);">Dialog 的背景、圆角、阴影、遮罩全部来自第一层 token。</p><template #footer><el-button @click="open = false">取消</el-button><el-button type="primary" @click="open = false">确定</el-button></template></el-dialog><el-dialog v-model="open2" title="居中对话框" align-center width="360"><p style="font-size: 13px;">align-center</p></el-dialog>` },
    { key: 'drawer', cat: 'feedback', name: 'Drawer', cn: '抽屉', tokens: ['--color-bg-overlay', '--color-bg-mask', '--layout-sidebar-w', '--z-drawer'], usage: '<el-drawer v-model="open" title="标题" size="var(--layout-sidebar-w)">…</el-drawer>',
      demo: `<div class="ds-row"><el-button @click="open = true">右侧抽屉</el-button><el-button @click="open2 = true">底部抽屉</el-button></div><el-drawer v-model="open" title="抽屉" size="var(--layout-sidebar-w)"><p style="font-size: 13px; color: var(--color-text-secondary);">宽度取 --layout-sidebar-w。</p></el-drawer><el-drawer v-model="open2" title="底部" direction="btt" size="200px"><p style="font-size: 13px;">direction=btt</p></el-drawer>` },
    { key: 'loading', cat: 'feedback', name: 'Loading', cn: '加载', command: 'ElLoading', note: '指令 / 服务', tokens: ['--color-primary', '--color-bg-mask'], usage: 'v-loading="loading" 或 ElLoading.service({ text })',
      demo: `<div class="ds-row" style="align-items: stretch;"><div v-loading="true" style="width: 200px; height: 100px; border: var(--border-w) solid var(--color-border-muted); border-radius: var(--radius-md); background: var(--color-bg-surface);"></div><div v-loading="true" element-loading-text="加载中…" style="width: 200px; height: 100px; border: var(--border-w) solid var(--color-border-muted); border-radius: var(--radius-md); background: var(--color-bg-surface);"></div><el-button @click="loading()">全屏 Loading 服务</el-button></div>` },
    { key: 'message', cat: 'feedback', name: 'Message', cn: '消息提示', command: 'ElMessage', tokens: ['--color-success', '--color-warning', '--color-danger', '--z-toast', '--shadow-md'], usage: "ElMessage({ type: 'success', message: '已保存' })",
      demo: `<div class="ds-row"><el-button size="small" @click="msg('success')">成功</el-button><el-button size="small" @click="msg('warning')">警告</el-button><el-button size="small" @click="msg('error')">错误</el-button><el-button size="small" @click="msg('info')">信息</el-button></div>` },
    { key: 'message-box', cat: 'feedback', name: 'Message Box', cn: '消息弹框', command: 'ElMessageBox', tokens: ['--color-bg-overlay', '--shadow-lg', '--radius-lg', '--z-dialog'], usage: "ElMessageBox.confirm('确认删除？', '提示', { type: 'warning' })",
      demo: `<div class="ds-row"><el-button size="small" @click="box()">confirm</el-button><el-button size="small" @click="alert()">alert</el-button><el-button size="small" @click="prompt()">prompt</el-button></div>` },
    { key: 'notification', cat: 'feedback', name: 'Notification', cn: '通知', command: 'ElNotification', tokens: ['--color-bg-overlay', '--shadow-lg', '--radius-lg', '--z-toast'], usage: "ElNotification({ title: '通知', message: '…', type: 'info' })",
      demo: `<div class="ds-row"><el-button size="small" @click="notify()">右上角通知</el-button><el-button size="small" @click="notifyBR()">右下角 · success</el-button></div>` },
    { key: 'popconfirm', cat: 'feedback', name: 'Popconfirm', cn: '气泡确认框', tokens: ['--color-bg-overlay', '--shadow-md', '--radius-md', '--color-warning'], usage: '<el-popconfirm title="确认删除？" @confirm="fn"><template #reference><el-button>删除</el-button></template></el-popconfirm>',
      demo: `<div class="ds-row"><el-popconfirm title="确认删除这条记录？" confirm-button-text="删除" cancel-button-text="取消"><template #reference><el-button type="danger" plain size="small">删除</el-button></template></el-popconfirm><el-popconfirm title="确认提交？" :hide-icon="true"><template #reference><el-button size="small">无图标</el-button></template></el-popconfirm></div>` },
    { key: 'popover', cat: 'feedback', name: 'Popover', cn: '气泡卡片', tokens: ['--color-bg-overlay', '--shadow-md', '--radius-md', '--color-border-muted'], usage: '<el-popover trigger="hover" content="…"><template #reference><el-button>hover</el-button></template></el-popover>',
      demo: `<div class="ds-row"><el-popover placement="top-start" title="标题" :width="200" trigger="hover" content="这是一段内容，背景来自 --color-bg-overlay。"><template #reference><el-button size="small">hover 触发</el-button></template></el-popover><el-popover placement="bottom" :width="200" trigger="click" content="点击触发"><template #reference><el-button size="small">click 触发</el-button></template></el-popover></div>` },
    { key: 'tooltip', cat: 'feedback', name: 'Tooltip', cn: '文字提示', tokens: ['--color-text-default', '--color-bg-surface', '--radius-md', '--font-size-caption'], usage: '<el-tooltip content="提示"><el-button>hover</el-button></el-tooltip>',
      demo: `<div class="ds-row"><el-tooltip content="dark 主题（默认）" placement="top"><el-button size="small">dark</el-button></el-tooltip><el-tooltip content="light 主题" effect="light" placement="top"><el-button size="small">light</el-button></el-tooltip><el-tooltip content="右侧" placement="right"><el-button size="small">right</el-button></el-tooltip><el-tooltip content="底部" placement="bottom"><el-button size="small">bottom</el-button></el-tooltip></div>` },

    /* ---------------- Others ---------------- */
    { key: 'divider', cat: 'others', name: 'Divider', cn: '分割线', tokens: ['--color-border-muted', '--color-text-muted', '--space-module-gap'], usage: '<el-divider content-position="left">分组</el-divider>',
      demo: `<div style="font-size: 13px; color: var(--color-text-secondary);">上方内容</div><el-divider /><div style="font-size: 13px; color: var(--color-text-secondary);">下方内容</div><el-divider content-position="left">带文字</el-divider><div class="ds-row"><span>左</span><el-divider direction="vertical" /><span>中</span><el-divider direction="vertical" /><span>右</span></div>` },
    { key: 'watermark', cat: 'others', name: 'Watermark', cn: '水印', tokens: ['--color-text-placeholder', '--font-size-caption'], usage: '<el-watermark content="内部资料">…</el-watermark>',
      demo: `<el-watermark content="内部资料 · 设计系统" :font="{ color: 'rgba(144, 147, 153, 0.25)' }"><div style="height: 120px; border-radius: var(--radius-md); background: var(--color-bg-surface); border: var(--border-w) solid var(--color-border-muted);"></div></el-watermark>` },
  ]

  const CUSTOM = [
    { key: 'ui-shell', name: 'UiShell', cn: '页面外壳', group: 'shell', source: 'ui/UiShell.vue', anatomy: ['ElMenu', 'ElDrawer', 'ElScrollbar', 'ElButton', '.l-inline', '.l-cluster'], props: [['title', 'string', '产品名'], ['menu', '{ key, label, disabled? }[]', '侧栏菜单'], ['activeKey', 'string', '当前高亮，key 与 hash 路由一致'], ['v-model:collapsed', 'boolean', '侧栏折叠']], slots: ['default（内容区，需 .l-page 包裹）', 'header-actions', 'logo'], events: ['select(key)', 'scroll({ scrollTop })'], tags: ['ui-shell'], wide: true, usage: '<ui-shell title="示例系统" :menu="menu" :active-key="state.route" v-model:collapsed="state.collapsed" @select="go"><div class="l-page">…</div></ui-shell>',
      demo: `<div style="height: 260px; border: var(--border-w) solid var(--color-border-muted); border-radius: var(--radius-lg); overflow: hidden; --layout-header-h: 44px;"><div style="zoom: 0.85; height: 100%; min-height: 0;"><ui-shell title="示例系统" :menu="tree.map(t => ({ key: String(t.id), label: t.label }))" :active-key="active" v-model:collapsed="open" @select="k => active = k" style="min-height: 100%; height: 100%;"><div class="l-page"><ui-page-header title="订单列表" subtitle="共 128 条"><template #actions><el-button size="small">刷新</el-button><el-button type="primary" size="small">新建</el-button></template></ui-page-header><section class="l-module"><div style="font-size: 12px; color: var(--color-text-muted);">内容区 · .l-page 包裹</div></section></div></ui-shell></div></div><div class="ds-stage-note">缩放预览；真实尺寸见原型模板 apps/prototypes/_template.html。侧栏折叠、小屏变抽屉均由组件内部处理。</div>` },
    { key: 'ui-tuner', name: 'UiTuner', cn: '调参浮窗', group: 'shell', source: 'ui/UiTuner.vue', anatomy: ['ElButton', 'ElScrollbar', 'ElSlider', 'ElColorPicker', 'ElInput'], props: [['title', 'string = 调参 · 第一层', '浮窗标题']], slots: [], events: [], tags: ['ui-tuner'], wide: true, usage: '<ui-tuner></ui-tuner>',
      demo: `<ui-tuner></ui-tuner>` },
    { key: 'ui-page-header', name: 'UiPageHeader', cn: '页头', group: 'page', source: 'ui/UiPageHeader.vue', anatomy: ['.l-page-header', '.l-cluster--end', '<h1>', '<small>'], props: [['title', 'string', '标题'], ['subtitle', 'string?', '副标题']], slots: ['breadcrumb（标题上方面包屑）', 'actions（右侧按钮组）'], events: [], tags: ['ui-page-header'], usage: '<ui-page-header title="订单列表" subtitle="共 128 条"><template #actions><el-button type="primary">新建</el-button></template></ui-page-header>',
      demo: `<div class="ds-outline" style="padding: 4px;"><ui-page-header title="订单列表" subtitle="共 128 条 · 最近更新 10 分钟前"><template #breadcrumb><span>订单管理</span><span class="ui-page-header__sep">/</span><span>订单列表</span></template><template #actions><el-button>导出</el-button><el-button type="primary"><el-icon class="el-icon--left"><Plus /></el-icon>新建订单</el-button></template></ui-page-header></div>` },
    { key: 'ui-state', name: 'UiState', cn: '状态容器', group: 'page', source: 'ui/UiState.vue', anatomy: ['ElSkeleton', 'ElEmpty', 'ElButton', '.l-state'], props: [['state', "'ready' | 'loading' | 'empty' | 'error'", 'ready 时渲染默认插槽'], ['emptyText / errorText', 'string?', '文案'], ['rows', 'number?', '骨架行数']], slots: ['default（ready 态内容）', 'action（empty 态操作）'], events: ['retry'], tags: ['ui-state'], usage: '<ui-state :state="state.view" @retry="load">…</ui-state>', init: 'ready',
      demo: `<div class="ds-row"><small class="ds-dim">state</small><el-radio-group v-model="v" size="small"><el-radio-button value="ready">ready</el-radio-button><el-radio-button value="loading">loading</el-radio-button><el-radio-button value="empty">empty</el-radio-button><el-radio-button value="error">error</el-radio-button></el-radio-group></div><div class="ds-outline" style="padding: 8px; min-height: 96px;"><ui-state :state="v" :rows="3" @retry="v = 'ready'"><div style="font-size: 13px; color: var(--color-text-secondary);">ready 态渲染默认插槽：这里是真实内容。</div></ui-state></div>` },
    { key: 'ui-list-item', name: 'UiListItem', cn: '列表项', group: 'composite', source: 'ui/composites/UiListItem.vue', anatomy: ['.l-cluster--between', '.l-inline', '.l-stack--tight', 'ElAvatar', 'ElTag'], props: [['title / subtitle', 'string', ''], ['avatar', 'string?', '取首字；给 leading 插槽时忽略'], ['status', '{ label, type? }', '右侧胶囊标签'], ['clickable', 'boolean', 'hover 高亮 + 右侧箭头'], ['active', 'boolean', '当前项，用 --color-bg-accent 高亮'], ['divided', 'boolean', '底部分割线']], slots: ['leading', 'trailing'], events: ['click'], tags: ['ui-list-item'], usage: '<ui-list-item title="成都示例科技" subtitle="SO-001 · 2026-09-01" avatar="成" :status="{ label: \'待处理\', type: \'warning\' }" clickable><template #trailing><el-button text type="primary" size="small">查看</el-button></template></ui-list-item>',
      demo: `<div class="l-stack l-stack--tight ds-outline" style="padding: 4px;"><ui-list-item v-for="(r, i) in rows" :key="r.no" :title="r.customer" :subtitle="r.no + ' · ' + r.date + ' · ' + r.amount.toLocaleString() + ' 元'" :avatar="r.customer" :status="{ label: opts.find(o => o.value === r.status).label, type: { pending: 'warning', done: 'success', cancelled: 'info' }[r.status] }" :active="i === 0" clickable divided><template #trailing><el-button text type="primary" size="small">查看</el-button></template></ui-list-item></div><div class="ds-stage-note">结构级下沉范例：原型里 data-composite="list-item" 出现第二次后封装而成；active 高亮当前项，clickable 时右侧显示箭头。</div>` },
    { key: 'ui-filter-bar', name: 'UiFilterBar', cn: '筛选条', group: 'composite', source: 'ui/composites/UiFilterBar.vue', anatomy: ['.l-toolbar', '.l-cluster', '.l-cluster--end', 'ElButton'], props: [['searchable', 'boolean = true', '搜索按钮（primary）'], ['resettable', 'boolean = true', '重置按钮'], ['advanced', 'boolean', '「高级搜索」；有 #advanced 插槽时弹浮窗'], ['searchText / resetText / advancedText', 'string', '文案']], slots: ['default（label + 控件对：<span class="l-inline"><small>标签</small><el-input/></span>）', 'advanced（高级搜索浮窗内容，展开不改变筛选条高度）', 'summary（右侧摘要）', 'actions（右侧按钮）'], events: ['search', 'reset', 'toggle(open)'], tags: ['ui-filter-bar'], wide: true, usage: '<ui-filter-bar advanced @search="load" @reset="reset"><span class="l-inline"><small>企业名称</small><el-input v-model="s.kw" clearable></el-input></span><template #advanced><span class="l-inline"><small>所属片区</small><el-select v-model="s.area"></el-select></span></template><template #actions><el-button type="primary">新增</el-button></template></ui-filter-bar>',
      demo: `<ui-filter-bar advanced @reset="s = ''"><span class="l-inline"><small>企业名称</small><el-input v-model="s" placeholder="请输入企业名称" clearable /></span><span class="l-inline"><small>运行状态</small><el-select v-model="v" placeholder="请选择" clearable><el-option v-for="o in opts" :key="o.value" :label="o.label" :value="o.value" /></el-select></span><template #advanced><span class="l-inline"><small>所属片区</small><el-select v-model="v2" placeholder="请选择" clearable><el-option label="东区" value="e" /><el-option label="西区" value="w" /></el-select></span><span class="l-inline"><small>行业类型</small><el-select placeholder="请选择" clearable><el-option label="生产制造" value="m" /></el-select></span></template><template #summary>已选 2 项</template><template #actions><el-button>导出</el-button><el-button type="primary">新增企业</el-button></template></ui-filter-bar>` },
    { key: 'ui-stat-card', name: 'UiStatCard', cn: '统计卡片', group: 'composite', source: 'ui/composites/UiStatCard.vue', anatomy: ['.l-module', '.l-inline', '<small>', 'slot'], props: [['label', 'string', '标签'], ['value', 'number | string', '数值为 number 时千分位'], ['unit', 'string?', '单位'], ['trend', 'number?', '百分比；0 显示持平'], ['upIsGood', 'boolean?', '不传→主色胶囊；传了→按好坏用语义色'], ['hint', 'string?', '说明（10px）']], slots: ['icon（右上角图标，此时趋势下移到数值行）', 'default（附加内容）'], events: [], tags: ['ui-stat-card'], wide: true, usage: '<ui-stat-card label="本月订单" :value="1280" unit="单" :trend="12.5" hint="较上月"></ui-stat-card>',
      demo: `<div class="l-grid l-grid--cols-4"><ui-stat-card label="园区企业" :value="286" :trend="12.5" hint="较上月变化" /><ui-stat-card label="成交金额" :value="2683400" unit="元" :trend="-3.2" :up-is-good="true" hint="语义色：下降为坏" /><ui-stat-card label="退货率" value="1.8%" :trend="0.4" :up-is-good="false" hint="语义色：上升为坏" /><ui-stat-card label="待处理" :value="37" :trend="0" hint="与昨日持平"><template #icon><el-icon><Clock /></el-icon></template></ui-stat-card></div><div class="ds-stage-note">不传 up-is-good 时趋势胶囊用主色（参考站风格）；传了则按语义色区分好坏；给 icon 插槽时趋势下移到数值行。</div>` },
    { key: 'ui-module-header', name: 'UiModuleHeader', cn: '模块标题行', group: 'composite', source: 'ui/composites/UiModuleHeader.vue', anatomy: ['.l-module-header', '<h2>', '<small>', '.l-cluster'], props: [['title', 'string', '标题（14 / 600）'], ['desc', 'string?', '描述（12 / muted）']], slots: ['meta（右侧，主色 12 / 500）'], events: [], tags: ['ui-module-header'], usage: '<section class="l-module"><ui-module-header title="企业服务趋势" desc="近七日服务请求数量"><template #meta>本周 434</template></ui-module-header>…</section>',
      demo: `<section class="l-module" style="max-width: 420px;"><ui-module-header title="企业服务趋势" desc="近七日服务请求数量"><template #meta>本周 434</template></ui-module-header><div class="l-bars" style="min-height: 96px;"><div v-for="(v, i) in [42, 58, 46, 72, 64, 82, 70]" :key="i"><span class="l-bar" :style="{ height: v + '%' }"></span><small>周{{ '一二三四五六日'[i] }}</small></div></div></section>` },
  ]

  const LAYOUTS = [
    { key: 'page', title: '.l-page / .l-page--fill', desc: '内容区容器：最大宽 + 页面内边距，直接子元素之间自动 page-gap；加 --fill 撑满外壳内容区，子项加 .l-fill 吃掉剩余高度（表格页）', tokens: ['--layout-content-max', '--space-page-pad-x', '--space-page-pad-y', '--space-page-gap'],
      demo: `<div class="l-page ds-outline" style="background: var(--color-bg-page); --layout-content-max: 100%;"><div class="ds-block">区块 1</div><div class="ds-block">区块 2 · 与上一个之间是 --space-page-gap</div></div>` },
    { key: 'module', title: '.l-module / .l-module-header', desc: '卡片 / 面板容器与标题行', tokens: ['--space-module-pad', '--space-module-title', '--color-bg-surface', '--color-border-muted', '--radius-lg'],
      demo: `<section class="l-module"><div class="l-module-header"><h2>模块标题</h2><span class="l-cluster"><el-button size="small">操作</el-button></span></div><div class="ds-block">内容 · 标题到内容是 --space-module-title</div></section>` },
    { key: 'stack', title: '.l-stack', desc: '纵向堆叠；--tight 用 component-gap，--loose 用 page-gap', tokens: ['--space-module-gap', '--space-component-gap', '--space-page-gap'],
      demo: `<div class="l-grid l-grid--cols-3"><div><small class="ds-dim">.l-stack</small><div class="l-stack"><div class="ds-block">row</div><div class="ds-block">row</div></div></div><div><small class="ds-dim">.l-stack--tight</small><div class="l-stack l-stack--tight"><div class="ds-block">row</div><div class="ds-block">row</div></div></div><div><small class="ds-dim">.l-stack--loose</small><div class="l-stack l-stack--loose"><div class="ds-block">row</div><div class="ds-block">row</div></div></div></div>` },
    { key: 'grid', title: '.l-grid / .l-span-*', desc: '栅格：默认 12 列，或 --cols-2/3/4；子项 .l-span-N 跨列；768px 以下降为单列', tokens: ['--grid-cols', '--grid-gap', '--breakpoint-md'],
      demo: `<div class="l-stack"><div><small class="ds-dim">.l-grid--cols-3</small><div class="l-grid l-grid--cols-3"><div class="ds-block">1</div><div class="ds-block">2</div><div class="ds-block">3</div></div></div><div><small class="ds-dim">.l-grid（12 列）+ .l-span-4 / .l-span-8</small><div class="l-grid"><div class="ds-block l-span-4">span-4</div><div class="ds-block l-span-8">span-8</div></div></div><div><small class="ds-dim">.l-grid--cols-4 .l-grid--tight</small><div class="l-grid l-grid--cols-4 l-grid--tight"><div class="ds-block">a</div><div class="ds-block">b</div><div class="ds-block">c</div><div class="ds-block">d</div></div></div></div>` },
    { key: 'split', title: '.l-split', desc: '侧栏 + 主区两栏；侧栏宽取 --layout-sidebar-w；--reverse 侧栏在右', tokens: ['--layout-sidebar-w', '--space-module-gap'],
      demo: `<div class="l-stack"><div class="l-split"><div class="ds-block">side</div><div class="ds-block">main</div></div><div class="l-split l-split--reverse"><div class="ds-block">main</div><div class="ds-block">side</div></div></div>` },
    { key: 'cluster', title: '.l-cluster / .l-toolbar', desc: '横向可换行（按钮组、筛选条）；工具条左筛选右操作；控件宽取 --layout-control-w', tokens: ['--space-component-gap', '--layout-control-w', '--space-module-title'],
      demo: `<div class="l-stack"><div class="l-cluster"><el-button>A</el-button><el-button>B</el-button><el-button>C</el-button></div><div class="l-cluster l-cluster--end"><el-button>取消</el-button><el-button type="primary">确定</el-button></div><div class="l-toolbar ds-outline"><span class="l-cluster"><el-input placeholder="搜索" clearable /><el-select placeholder="状态" clearable><el-option label="待处理" value="p" /></el-select></span><span class="l-cluster l-cluster--end"><el-button>重置</el-button><el-button type="primary">新建</el-button></span></div></div>` },
    { key: 'form', title: '.l-form', desc: '表单区块：label 列宽取 --layout-form-label-w', tokens: ['--layout-form-label-w', '--space-component-title'],
      demo: `<el-form class="l-form" label-position="right"><div class="l-grid l-grid--cols-2"><el-form-item label="客户名称"><el-input placeholder="请输入" /></el-form-item><el-form-item label="状态"><el-select placeholder="请选择"><el-option label="待处理" value="p" /></el-select></el-form-item></div></el-form>` },
    { key: 'inline', title: '.l-inline / .l-state', desc: '行内：图标 + 文字；状态容器：loading / empty / error 占位（UiState 内部使用）', tokens: ['--space-inline-gap', '--layout-control-w-sm', '--space-page-gap'],
      demo: `<div class="l-stack"><div class="l-cluster" style="gap: var(--space-6);"><span class="l-inline"><el-icon><Clock /></el-icon>10 分钟前</span><span class="l-inline"><el-icon style="color: var(--color-success);"><CircleCheck /></el-icon>已完成</span><span class="l-inline"><small>密度</small><el-select size="small" placeholder="默认"><el-option label="默认" value="d" /></el-select></span></div><div class="l-state ds-outline"><el-icon style="font-size: 24px;"><Warning /></el-icon><span>.l-state · 加载失败</span><el-button size="small">重试</el-button></div></div>` },
  ]

  const DESC = {
    '--color-bg-page': '页面底色', '--color-bg-surface': '卡片 / 表格 / 输入框表面', '--color-bg-subtle': '斑马纹、hover 行', '--color-bg-muted': '禁用、次级填充', '--color-bg-accent': '主色柔和底：选中行、强调面板', '--color-bg-overlay': '弹层背景', '--color-bg-mask': '遮罩',
    '--color-text-default': '正文', '--color-text-secondary': '次要文字、表格内容', '--color-text-muted': '辅助说明', '--color-text-placeholder': '占位符、禁用文字', '--color-text-inverse': '深色底上的文字',
    '--color-border-default': '输入框、表格外框', '--color-border-muted': '分割线、卡片边', '--color-icon-default': '图标', '--color-icon-muted': '次级图标',
    '--color-primary': '主按钮 / 链接 / 选中', '--color-primary-hover': '主色 hover', '--color-success': '成功', '--color-warning': '警告', '--color-danger': '危险 / 错误', '--color-danger-hover': '危险 hover', '--color-info': '中性信息',
    '--layout-sidebar-w': '侧栏宽', '--layout-sidebar-w-collapsed': '侧栏折叠宽', '--layout-header-h': '顶栏高', '--layout-content-max': '内容区最大宽', '--layout-content-pad': '内容区内边距（= page-pad-x）', '--layout-form-label-w': '表单标签列宽', '--layout-control-w': '工具条控件宽', '--layout-control-w-sm': '小控件宽', '--grid-cols': '栅格列数', '--grid-gap': '栅格间隙', '--breakpoint-md': '中屏断点', '--breakpoint-lg': '大屏断点',
    '--z-header': '顶栏', '--z-sidebar': '侧栏', '--z-drawer': '抽屉', '--z-dialog': '对话框 / popper', '--z-toast': '消息',
    '--font-family': '正文字体', '--font-family-mono': '代码 / 变量名', '--line-height-tight': '标题行高', '--line-height-body': '正文行高', '--font-weight-regular': '常规', '--font-weight-medium': '中等', '--font-weight-bold': '加粗',
  }

  /* 配色预设：候选默认色，选定后写入 tokens.css。值只覆盖语义层，dark 重映射仍生效 */
  /* 配色预设：真值在 tokens.css ⑤ 段（[data-palette]），这里只登记 key / label 供展示页切换 */
  const PRESETS = [
    { key: 'cyan', label: '科技青（默认）' },
    { key: 'element', label: 'Element 蓝' },
    { key: 'indigo', label: '清爽 · 靛蓝' },
    { key: 'violet', label: '清爽 · 靛紫' },
  ]

  /* ---------------- 布局配置 · 五套页面排版模板（参考 HY Compiler Studio · 页面排版模板） ----------------
   * 每套模板 = 在同一个 UiShell 应用壳内，用第一层 .l-* + 第二层白名单 / 自研组件拼出的页面骨架。
   * skeleton 即可直接复制进原型 .l-page 内的内容；stage 只是加了应用壳的预览。 */
  const APP_MENU = [
    { key: 'dashboard', label: '运营工作台' }, { key: 'monitor', label: '运行监测' }, { key: 'company', label: '企业档案' },
    { key: 'device', label: '设备台账' }, { key: 'org', label: '组织与片区' }, { key: 'env', label: '环境监测' }, { key: 'risk', label: '风险预警' },
  ]
  const STAT_ROW = `<div class="l-grid l-grid--cols-4"><ui-stat-card label="园区企业" :value="286" :trend="12.5" hint="较上月变化" /><ui-stat-card label="在建项目" :value="38" :trend="6.2" hint="较上月变化" /><ui-stat-card label="待办事项" :value="19" :trend="-3.8" hint="较上月变化" /><ui-stat-card label="风险预警" :value="6" :trend="-16.7" hint="较上月变化" /></div>`
  const TABLE_MODULE = (title, cols) => `<section class="l-module l-stack l-stack--tight l-fill"><ui-filter-bar advanced @reset="s = ''"><span class="l-inline"><small>${cols[0]}</small><el-input v-model="s" placeholder="请输入${cols[0]}" clearable /></span><span class="l-inline"><small>${cols[2]}</small><el-select v-model="v" placeholder="请选择" clearable><el-option v-for="o in opts" :key="o.value" :label="o.label" :value="o.value" /></el-select></span><template #advanced><span class="l-inline"><small>所属片区</small><el-select v-model="v2" placeholder="请选择" clearable><el-option label="东区" value="e" /><el-option label="西区" value="w" /></el-select></span><span class="l-inline"><small>行业类型</small><el-select placeholder="请选择" clearable><el-option label="生产制造" value="m" /></el-select></span></template><template #actions><el-button>导出</el-button><el-button type="primary"><el-icon class="el-icon--left"><Plus /></el-icon>${title}</el-button></template></ui-filter-bar><el-table class="l-fill" :data="rows"><el-table-column type="index" label="序号" width="56" /><el-table-column prop="customer" label="${cols[0]}" min-width="180" show-overflow-tooltip /><el-table-column prop="no" label="${cols[1]}" width="170" class-name="ds-mono" /><el-table-column label="${cols[2]}" width="110"><template #default="{ row }"><el-tag size="small" round :type="{ pending: 'warning', done: 'success', cancelled: 'info' }[row.status]">{{ opts.find(o => o.value === row.status).label }}</el-tag></template></el-table-column><el-table-column prop="date" label="更新时间" width="120" /><el-table-column label="操作" width="120" fixed="right" class-name="is-actions"><template #default><el-button link type="primary" size="small">查看</el-button><el-button link type="primary" size="small">编辑</el-button></template></el-table-column></el-table><div class="l-cluster l-cluster--end"><el-pagination layout="total, prev, pager, next, sizes" :total="128" v-model:current-page="page" v-model:page-size="pageSize" :page-sizes="[10, 20, 50]" /></div></section>`
  const CRUMB = (a, b) => `<small class="l-inline" style="color: var(--color-text-muted);"><el-icon style="color: var(--color-primary);"><HomeFilled /></el-icon><span>${a}</span><span style="color: var(--color-text-placeholder);">/</span><span style="color: var(--color-text-default); font-weight: var(--font-weight-medium);">${b}</span></small>`

  const TEMPLATES = [
    { key: 'stat', no: '01', label: '统计模板', route: 'dashboard', crumb: ['园区运营', '运营工作台'], desc: '只展示统计与分析模块之间的间距：统计卡行 → 趋势 / 分布 → 概况 → 进度',
      anatomy: ['面包屑', '.l-grid--cols-4', 'UiStatCard ×4', '.l-grid--main-aside', '.l-module', 'UiModuleHeader', '.l-bars', '.l-tile', 'ElProgress'],
      skeleton: `${CRUMB('园区运营', '运营工作台')}
${STAT_ROW}
<div class="l-grid l-grid--main-aside">
  <section class="l-module l-stack l-stack--tight"><ui-module-header title="企业服务趋势" desc="近七日服务请求数量"><template #meta>本周 434</template></ui-module-header><div class="l-bars"><div v-for="(d, i) in [['周一', 42], ['周二', 58], ['周三', 46], ['周四', 72], ['周五', 64], ['周六', 82], ['周日', 70]]" :key="d[0]"><span class="l-bar" :style="{ height: d[1] + '%' }"></span><small>{{ d[0] }}</small></div></div></section>
  <section class="l-module"><ui-module-header title="企业类型分布" desc="当前入驻企业构成"></ui-module-header><div class="l-stack l-stack--tight"><div v-for="d in [['生产制造', 82, 88], ['仓储物流', 64, 69], ['研发办公', 48, 52], ['园区服务', 32, 35]]" :key="d[0]" class="l-stack" style="gap: var(--space-inline-gap);"><div class="l-cluster l-cluster--between"><small>{{ d[0] }}</small><strong>{{ d[1] }}</strong></div><el-progress :percentage="d[2]" :show-text="false" :stroke-width="8" /></div></div></section>
  <section class="l-module"><ui-module-header title="园区运营概况" desc="招商、服务、巡检与能耗关键结果"><template #meta>今日更新</template></ui-module-header><div class="l-grid l-grid--cols-2 l-grid--tight"><div v-for="c in [['招商签约', '推进中', '18 家', '年度目标完成 72%'], ['企业服务', '运行平稳', '46 项', '本月按期办结 43 项'], ['设备巡检', '已闭环', '128 次', '发现并闭环隐患 11 项'], ['能耗优化', '优于目标', '8.6%', '综合能耗同比下降']]" :key="c[0]" class="l-tile l-stack" style="gap: var(--space-inline-pad);"><div class="l-cluster l-cluster--between"><small>{{ c[0] }}</small><small style="color: var(--color-primary); font-weight: var(--font-weight-medium);">{{ c[1] }}</small></div><strong style="font-size: var(--font-size-module-title); font-weight: var(--font-weight-bold); margin-top: var(--space-inline-pad);">{{ c[2] }}</strong><small style="font-size: var(--font-size-micro);">{{ c[3] }}</small></div></div></section>
  <section class="l-module"><ui-module-header title="年度任务进度" desc="重点经营目标完成情况"></ui-module-header><div class="l-stack l-stack--tight"><div v-for="t in [['年度招商任务', 72, '36 / 50 家'], ['重点项目建设', 64, '16 / 25 项'], ['企业诉求办结', 94, '188 / 200 件'], ['风险隐患闭环', 88, '44 / 50 项']]" :key="t[0]" class="l-stack" style="gap: var(--space-inline-gap);"><div class="l-cluster l-cluster--between"><small>{{ t[0] }}</small><strong style="font-size: var(--font-size-caption);">{{ t[2] }}</strong></div><el-progress :percentage="t[1]" :show-text="false" :stroke-width="8" /></div></div></section>
</div>` },
    { key: 'table', no: '02', label: '纯表格页', route: 'company', crumb: ['资产运营', '企业档案'], desc: '标准查询 + 表格结构：页头操作 → 筛选条（可展开高级搜索）→ 表格 → 分页',
      anatomy: ['面包屑', '.l-module', 'UiFilterBar', 'ElTable', 'ElPagination'],
      skeleton: `${CRUMB('资产运营', '企业档案')}
${TABLE_MODULE('新增企业', ['企业名称', '统一编码', '运行状态'])}` },
    { key: 'stat-table', no: '03', label: '统计 + 表格', route: 'monitor', crumb: ['园区运营', '运行监测'], desc: '统计模块与列表模块上下组合：统计卡行 → 表格模块',
      anatomy: ['面包屑', '.l-grid--cols-4', 'UiStatCard ×4', '.l-module', 'UiFilterBar', 'ElTable', 'ElPagination'],
      skeleton: `${CRUMB('园区运营', '运行监测')}
${STAT_ROW}
${TABLE_MODULE('新增设备', ['设备名称', '设备编号', '设备状态'])}` },
    { key: 'tree-table', no: '04', label: '左树 + 表格', route: 'org', crumb: ['安全环保', '组织与片区'], desc: '左侧组织树与列表模块左右组合：.l-split 左树右表',
      anatomy: ['面包屑', '.l-split--aside', '.l-module', 'UiModuleHeader', 'ElTree', 'UiFilterBar', 'ElTable', 'ElPagination'],
      skeleton: `${CRUMB('安全环保', '组织与片区')}
<div class="l-split l-split--aside l-fill">
  <section class="l-module"><ui-module-header title="园区组织树" desc="TreeListSimple · 纯前端递归树"><template #meta><el-tag size="small" type="info" round>全部</el-tag></template></ui-module-header><div class="l-stack l-stack--tight"><el-input placeholder="搜索节点" clearable><template #prefix><el-icon><Search /></el-icon></template></el-input><el-tree :data="[{ id: 0, label: '全部园区', children: [{ id: 1, label: '东区', children: [{ id: 11, label: 'A 栋' }, { id: 12, label: 'B 栋' }] }, { id: 2, label: '西区', children: [{ id: 21, label: 'C 栋' }] }, { id: 3, label: '南区' }] }]" node-key="id" default-expand-all highlight-current :current-node-key="0" /></div></section>
  ${TABLE_MODULE('新增企业', ['企业名称', '统一编码', '运行状态'])}
</div>` },
    { key: 'tabs-table', no: '05', label: 'TabBar + 表格', route: 'env', crumb: ['安全环保', '环境监测'], desc: '线性页签导航与表格页上下组合：ElTabs.is-tabbar 胶囊页签条 → 表格模块',
      anatomy: ['面包屑', 'ElTabs.is-tabbar（skins/tabs.css）', '.l-module', 'UiFilterBar', 'ElTable', 'ElPagination'],
      skeleton: `${CRUMB('安全环保', '环境监测')}
<el-tabs v-model="active" class="is-tabbar"><el-tab-pane label="企业档案" name="a" /><el-tab-pane label="设备台账" name="b" /><el-tab-pane label="环境监测" name="c" /><el-tab-pane label="风险预警" name="d" /></el-tabs>
${TABLE_MODULE('新增监测点位', ['监测点位', '点位编号', '数据状态'])}` },
  ]
  for (const t of TEMPLATES) {
    // 骨架里有 .l-fill 的（表格页）页面撑满外壳内容区；纯统计页保持自然流
    t.pageClass = t.skeleton.includes('l-fill') ? 'l-page l-page--fill' : 'l-page'
    t.demo = `<ui-shell title="智慧园区运营平台" :menu="menu" :active-key="'${t.route}'" v-model:collapsed="open2" style="height: 100%; min-height: 0;"><template #header-actions><el-tag v-for="h in history" :key="h" size="small" :effect="h === '${t.crumb[1]}' ? 'dark' : 'plain'" closable>{{ h }}</el-tag><el-button text circle><el-icon><Bell /></el-icon></el-button><el-tag effect="plain" round><el-icon class="el-icon--left"><User /></el-icon>园区管理员</el-tag></template><div class="${t.pageClass}">${t.skeleton}</div></ui-shell>`
    t.initActive = 'c'
  }

  /* 自研组件消费的 token 由 scripts/check-layer2.mjs 从源码扫描生成（dist/token-coverage.js），不再手工登记 */
  for (const c of CUSTOM) c.tokens = (window.DS_COVERAGE && window.DS_COVERAGE.components[c.name]) || []

  return { ROUTES, CATEGORIES, CUSTOM_GROUPS, COMPONENTS, CUSTOM, LAYOUTS, DESC, SAMPLE, PRESETS, TEMPLATES, APP_MENU }
})()
